server:
  port: 18081


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dev_local?autoReconnect=True&useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul #jdbc:h2:mem:testdb
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  security:
    user:
      password: 1

logging:
  level:
    root: info